<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 4:  Using Yelp cost estimates for estimating neighborhood affluency

<i>
                
                Submitted by Shannon Bingham and Roy Kim
</i>

 
## Problem Statement
This tool will estimate the affluence of a neighborhood based on the number of `$` of businesses and services (according to Yelp) in a given neighborhood. (`$`, `$$`, `$$$`, `$$$$`) This tool will expect to get, as an input, a list of zip codes or names of neighborhoods and will estimate the wealth of the locality. While traditional methods typically estimate wealth of a locality based on demographic characteristics (e.g. income or unemployment rate), the novelty of this approach is in its use of big data related to commercial activity and cost of product and services as an indicator for affluency.

## Notebook Description
_This notebook will be used as a preliminary modeling tool, grabbing 10 zip codes' data from http://www.city-data.com and the Yelp API. We will then create an unsupervised model, using KMeans and DBSCAN to cluster the data. If time allows, we will also use a supervised model with median income as our target._

In [2]:
import pandas as pd
import numpy as np
import json
from zip_extract import zip_data
from time import sleep
from IPython.display import display
from yelp_keys import keys
from yelpapi import YelpAPI

In [3]:
df = pd.read_csv('../data/WIzips.csv', header=None)
df.columns = {'zipcode'}
df = df.astype(str)
df.head()

  zipcode
0   53001
1   53002
2   53003
3   53004
4   53005

In [4]:
yelp = YelpAPI(keys['api_key'])

In [ ]:
# Using the Yelp API to retrieve the number of businesses per zip code

# zip_bus_list = []
# for zipcode in df['zipcode']:
#     search = yelp.search_query(location=zipcode, limit=1)
#     zip_bus_list.append(search['total'])

In [ ]:
# Converting the list of businesses into a Series, and then into a DataFrame
# that includes the zip code and number of businesses

# zip_bus_list_series = pd.Series(zip_bus_list)
# df_business = pd.concat([df, zip_bus_list_series],axis=1)
# df_business = df_business.rename(columns= {0 : 'n_business'})

# Saving that DataFrame into a csv file for later use
# df_business.to_csv('../data/wi_zip_business.csv', index = False)

In [5]:
# Reading in the previous DataFrame to avoid rerunning Yelp API
df_business = pd.read_csv('../data/wi_zip_business.csv')
df_business.head()

   zipcode  n_business
0    53001          24
1    53002         191
2    53003           2
3    53004         105
4    53005        2800

### Decision to only use zip codes that have between 50 and 1000 businesses
_This decision had to be made due to the limitations on the Yelp API (1000 retrievals per API call). In a running business model, this limitation could be skipped if a paid business account is made with Yelp._

In [6]:
# Only choosing zip codes that have between 50 and 1000 businesses
df_avail = df_business[(df_business['n_business'] < 1000) & (df_business['n_business'] > 50)]

In [19]:
pd.set_option('display.max_rows', 800)

In [20]:
df_avail

     zipcode  n_business
1      53002         191
3      53004         105
5      53006          83
9      53012         524
10     53013          61
14     53017         207
15     53018         148
16     53019         163
18     53021         200
19     53022         160
20     53023          92
21     53024         152
22     53027         218
23     53029         221
26     53033         424
27     53034          93
28     53035          97
29     53036         230
30     53037         461
31     53038         158
32     53039          69
33     53040          69
36     53045         581
38     53047         156
42     53051         252
43     53057         111
44     53058         174
45     53059         124
46     53061          71
47     53063         129
48     53065         168
49     53066         144
51     53070         206
52     53072         299
53     53073         126
54     53074          52
56     53076         335
57     53078          62
59     53080         276
60     53081         242
61     53083         259
62     53085          79
63     53086         301
65     53089         854
66     53090         107
67     53091          67
68     53092         191
69     53093         107
70     53094          69
71     53095         102
72     53097         643
73     53098          76
74     53103         661
75     53104         694
76     53105          94
77     53108         859
78     53110         181
79     53114         162
80     53115         225
81     53118         281
82     53119         130
83     53120          52
84     53121          90
85     53122         239
86     53125         319
87     53126         161
88     53128         349
89     53129         225
90     53130          60
92     53137         195
93     53139         237
94     53140         288
95     53142         650
96     53143         205
97     53144         318
99     53147         182
101    53150         264
102    53151         588
103    53153          51
104    53154         426
105    53156         109
106    53158         667
108    53168          63
110    53172         134
111    53177         150
112    53178         177
113    53179          56
115    53182          55
116    53183          99
118    53185         287
119    53186         408
120    53188         795
121    53189         311
125    53202         839
126    53203         555
127    53204         915
128    53205         909
129    53206         669
131    53208         484
136    53213         390
139    53216         183
140    53217         442
141    53218         126
142    53219         355
143    53220         305
145    53222         830
146    53223         396
147    53224         305
148    53225         129
149    53226         934
150    53227         268
151    53228         208
152    53233         993
153    53235         275
154    53402         454
155    53403         148
156    53404         174
157    53405         188
158    53406         284
161    53503          76
163    53505         273
168    53511         160
169    53515          90
174    53521          65
175    53522          58
176    53523         163
177    53525         288
180    53528         559
181    53529          80
183    53531         243
184    53532         191
186    53534          66
193    53545         225
194    53546         234
195    53548         126
196    53549          84
197    53550          79
207    53561          92
208    53562         398
209    53563         120
217    53574          53
219    53576         153
223    53580          52
225    53582          53
227    53585         197
231    53589          91
232    53590         223
233    53593         281
235    53597         315
236    53598         143
237    53703         579
238    53704         855
239    53705         934
240    53706         380
242    53713         901
243    53714         280
244    53715         597
245    53716         830
246    53717         253
248    53719         663
264    53821          57
268    53901          60
270    53911         171
271    53913         271
272    53916          53
275    53922         113
281    53930          57
282    53931          77
284    53933          91
292    53944         156
297    53951          57
305    53961         191
308    53965         124
313    54003          65
318    54009          55
321    54014          79
323    54016         217
326    54021          64
328    54023         206
330    54025         123
334    54082         352
344    54113         113
346    54115         506
356    54130         175
358    54136         123
359    54137          53
362    54140         324
364    54143          79
367    54151          65
370    54155         511
378    54166          51
379    54169          56
381    54171          62
382    54173         406
388    54202          92
392    54209         112
395    54212         114
400    54220         112
402    54228          62
403    54229         287
406    54234         138
407    54235          70
409    54245          77
411    54247         149
412    54301         509
413    54302         452
414    54303         425
415    54304         476
417    54311         278
418    54313         585
419    54401         190
420    54403          84
431    54416         114
436    54423          60
447    54441          76
453    54449          68
466    54466          65
467    54467          69
468    54469          72
470    54471         124
472    54474         104
473    54475          79
474    54476         186
475    54479          60
477    54481         166
478    54482         170
488    54494          72
492    54501          64
500    54521          61
528    54560          98
531    54564          66
533    54568         128
534    54601         286
535    54603         276
545    54621          95
549    54625         421
566    54650         205
581    54669          92
583    54701         243
584    54703         252
585    54720         220
588    54723          88
594    54729         157
611    54749          72
613    54751          60
627    54769          62
643    54822          53
644    54824          51
669    54858          59
691    54901         286
692    54902         195
693    54904         216
695    54911         431
696    54913         453
697    54914         412
698    54915         467
707    54932         128
708    54935         128
709    54937         125
712    54942         125
714    54944         114
720    54952         505
721    54956         372
726    54964          70
732    54971          55
733    54974         104
734    54977          76
735    54979          85

### From the available zip codes, only 50 were chosen
_This was also due to the limitations of the Yelp API (only 5000 retrievals per day)._

In [9]:
# Choosing 50 random zipcodes from the available list
np.random.seed(42)
zip_list = np.random.choice(df_avail['zipcode'], 50, replace=False)

not_in_zip_list = []
for z in df_avail['zipcode']:
    if z not in zip_list:
        not_in_zip_list.append(z)

len(not_in_zip_list)

218

In [12]:
new_zip_list = np.random.choice(not_in_zip_list, 50, replace=False)

In [13]:
len(new_zip_list)

50

# Dividing the list of zip codes
_Due to the limitations of the Yelp API, we had to divide the zip code list into two lists so that we could retrieve the data._

In [155]:
zip_list = zip_list.tolist()

r_list = [53018,53034,53038,53057,53086,53091,53092,53119,53179,
          53189,53206,53406,53522,53528,53585,53703,53714,53916,
          54130,54235,54311,54466,54701,54720,54915]

shan_list = []
for r in zip_list:
    if r not in r_list:
        shan_list.append(r)

# Retrieving data from city-data.com

### We used https://www.city-data.com to retrieve population, area (sq. miles), median income, and cost of living index
_The Python script to retrieve this data is available in the same folder as this notebook._

In [76]:
# Retrieving data from city-data.com
# Zipcode, population, area, median income, cost of living
data = []
for zipcode in new_zip_list:
    print(zipcode)
    try:
        data.append(zip_data(zipcode))
    except:
        print(f'Unable to retrieve zipcode data for {zipcode}')
df_city_data = pd.DataFrame(data, columns = data[0].keys())

53403
54423
53045
53545
53405
53719
54621
53561
53065
53129
53525
53168
53154
54136
53051
53130
54025
54082
53128
53233
53186
53022
53202
54212
Unable to retrieve zipcode data for 54212
53225
53086
54466
53092
54235
53522
53091
53585
53018
54720
53714
53179
53406
53057
54311
53528
53038
53206
53916
54701
54130
53189
53703
53034
54915
53119

*Since the `zip_data` function was unable to retrieve data for zipcode 54212, we can manually get that info and put into the DataFrame.*

In [77]:
# Manually adding zipcode data for 54212
df_city_data = df_city_data.append({
    'zip' : 54212,
    'population' : 1125,
    'cost_of_living' : 90.7,
    'area' : 32.9,
    'median_income' : 78892
    }, ignore_index=True)

In [78]:
# Converting zipcodes from df_city_data into int
df_city_data['zip']=df_city_data['zip'].astype(int)

In [79]:
# Renaming zip column to 'zipcode'
df_city_data = df_city_data.rename(columns={'zip' : 'zipcode'})

In [80]:
df_city_data.to_csv('../data/zip_city.csv',index=False)

# Using the Yelp API to retrieve the data
_Using an iterative process, I first retrieved the data for the first 10 zip codes, then the next 10, then the remaining. The following loop retrieves the data for each zip code and saves that data into its own separate csv file._

In [30]:
regrab = [54521, 54166, 54822, 53704, 544449, 54003, 53213, 54228, 53006, 53216]

In [16]:
df_yelp = pd.DataFrame()

In [32]:
for zip_code in regrab:
    print(f'Retrieving from {zip_code}')
    # Retrieve up to 1000 businesses in a zip code
    for i in range(20):
        search = yelp.search_query(location=zip_code, offset = i*50, limit=50)
        n_total = search['total']
        df = pd.DataFrame(search['businesses'])
        df_yelp = df_yelp.append(df)
        print(f'Size of current retrieval {df_yelp.shape}')
        print(f'Retrieving businesses from {50*i}...')
        sleep(1)
        if (i*50 > n_total):
            break
    
    # Dropping rows that are missing 'price' or 'rating'
    for index, row in df_yelp.iterrows():
        if (row['price'] == None) or (row['rating'] == None):
            df_yelp = df_yelp.drop(row)
    
    
    df_yelp.to_csv(f'../data/full_yelp_zipcodes/yelp_api_zip{zip_code}.csv',index=False)
    
    # Resetting df_yelp
    df_yelp = pd.DataFrame(columns=df.columns)

Retrieving from 54521
Size of current retrieval (50, 16)
Retrieving businesses from 0...
Size of current retrieval (56, 16)
Retrieving businesses from 50...
Size of current retrieval (56, 16)
Retrieving businesses from 100...
Retrieving from 54166
Size of current retrieval (50, 16)
Retrieving businesses from 0...
Size of current retrieval (50, 16)
Retrieving businesses from 50...
Size of current retrieval (50, 16)
Retrieving businesses from 100...
Retrieving from 54822
Size of current retrieval (46, 16)
Retrieving businesses from 0...
Size of current retrieval (46, 16)
Retrieving businesses from 50...
Retrieving from 53704
Size of current retrieval (50, 16)
Retrieving businesses from 0...
Size of current retrieval (100, 16)
Retrieving businesses from 50...
Size of current retrieval (150, 16)
Retrieving businesses from 100...
Size of current retrieval (200, 16)
Retrieving businesses from 150...
Size of current retrieval (250, 16)
Retrieving businesses from 200...

KeyboardInterrupt:

### All data from city-data.com and Yelp have been retrieved
_Next steps would be to combine the datasets to later be analyzed._